### ISSUE TITLE
能分享下测试CBCT数据嘛

### ISSUE THREAD

**Issue by Qianxunha** [1DreamCollector/Tooth-and-alveolar-bone-segmentation-from-CBCT-main#2]
感谢博主提供的代码，能分享下测试CBCT数据嘛，
可以的话，十分感谢。这是我邮箱：1634568659@qq.com

**Comment by TingM26** [comment]
> 感谢博主提供的代码，能分享下测试CBCT数据嘛， 可以的话，十分感谢。这是我邮箱：[1634568659@qq.com](mailto:1634568659@qq.com)

您好，请问您获得数据了吗，如果有的话，可以麻烦发送给我一份吗，这是我的邮箱：1692557820@qq.com

**Comment by Qianxunha** [comment]
> > 感谢博主提供的代码，能分享下测试CBCT数据嘛， 可以的话，十分感谢。这是我邮箱：[1634568659@qq.com](mailto:1634568659@qq.com)
> 
> 您好，请问您获得数据了吗，如果有的话，可以麻烦发送给我一份吗，这是我的邮箱：[1692557820@qq.com](mailto:1692557820@qq.com)

没有，他没数据

**Comment by 1DreamCollector** [comment]
> > 感谢博主提供的代码，能分享下测试CBCT数据嘛， 可以的话，十分感谢。这是我邮箱：[1634568659@qq.com](mailto:1634568659@qq.com)
> 
> 您好，请问您获得数据了吗，如果有的话，可以麻烦发送给我一份吗，这是我的邮箱：[1692557820@qq.com](mailto:1692557820@qq.com)
我无权公开别人的数据，毕竟这个数据也是要跟他申请才能得到，不过，你可以用别的CT数据实验，这并不矛盾
