### ISSUE TITLE
two stage dataset generation

### ISSUE THREAD

**Issue by TingM26** [1DreamCollector/Tooth-and-alveolar-bone-segmentation-from-CBCT-main#3]
你好，请问怎么生成single tooth segmentation的dataset呢，训练过程中需要boundary、keypoints等信息，虽然在tooth_detection\dataloaders文件夹下有生成boundary、keypoints的代码，但是在single tooth segmentation的data_generation中却没有保存进h5文件中，请问该怎么解决呢

**Comment by TingM26** [comment]
没事了，我们对keypoints处理方法不约而同😊😊

**Comment by puppy2000** [comment]
> 没事了，我们对keypoints处理方法不约而同😊😊

您好，能否请教下kp的处理。我得到的结果感觉不太对

**Comment by simzhangbest** [comment]
> 没事了，我们对keypoints处理方法不约而同😊😊

请问你是如何搞定的，付费求支持
